export default{
    EN: {
        HeaderText:"Count the Pictures",
        StartGameHeaderText: "Start a New Game",
        UserChoiceInputText: "Select a Number",
        ResetButtonText: "Reset",
        ConfirmButtonText: "Confirm",
        StartGameButtonText: "Start Game",
        SelectedNumberHelpText:"You have selected",
        OpponentGuessHelpText: "Opponent's Guess",
        LowerButtonText: "Lower",
        GreaterButtonText: "Greater",
        GameOverHeaderText: "Game Over !!!",
        NumberOfRoundsHelpText:"Number of Rounds",
        StartNewGameButtonText: "New Game",
        InvalidNumberAlertTitle: "Invalid Number!", 
        InvalidNumberErrorDescription: "Enter a valid number between 1 and 99.",
        OkayButtonText: "Okay",
        FalseButtonAlertTitle:'Don\'t Lie!', 
        FalseButtonAlertDescription: "You know that",
        SorryButtonText: "Sorry!",
        IntroductionText: "Count the pictures with in the timeout",
        IntroductionTitle: "How to Play?",
        LevelSelctionTitle: "Select your Level",
        LevelOneTitle: "Level 1",
        LevelTwoTitle: "Level 2",
        LevelThreeTitle: "Level 3",
        LevelFourTitle: "Level 4",
        LevelTitleText: "Level",
        RoundTitleText: "Round",        
        GetStartedButtonText: "Get Started",
        NextRoundButtonText: 'Next',
        ResultFailText: 'Try Again',
        ResultPassText: 'Great!!!',
        ResultHelpText: 'Please select the correct answer',
        SelectCountHelpText: 'Select the Count',
        ResultSummaryTitle: 'Result Summary',
        TotalRoundsTitle: 'Total Rounds',
        PassResultTitle: 'Pass',
        FailResultTitle: 'Fail',
        ScoreTitle: 'Score',
        GameOverTitle: 'Game Over'
    },
    TL: {
        HeaderText:"బొమ్మలు లెక్కిద్దాం",
        StartGameHeaderText: "కొత్త ఆట ప్రారంభించు",
        UserChoiceInputText: "సంఖ్య ను ఎంచుకో",
        ResetButtonText: "రద్దు చేయి",
        ConfirmButtonText: "ఎంచుకో",
        StartGameButtonText: "ఆట ప్రారంభించు",
        SelectedNumberHelpText:"మీరు ఎంచుకున్న సంఖ్య",
        OpponentGuessHelpText: "ప్రత్యర్థి ఊహించిన సంఖ్య",
        LowerButtonText: "చిన్నది",
        GreaterButtonText: "పెద్దది",  
        GameOverHeaderText: "ఆట ముగిసింది !!!",
        NumberOfRoundsHelpText:"మొత్తం రౌండ్లు",
        StartNewGameButtonText: "కొత్త ఆట",
        InvalidNumberAlertTitle: "ఈ సంఖ్య  చెల్లదు!", 
        InvalidNumberErrorDescription: "మీరు ఎంచుకునే సంఖ్య  1 నుండి 99 మధ్యలోనే ఉండాలి.",
        OkayButtonText: "సరే",
        FalseButtonAlertTitle:'ఇది నిజం కాదు!', 
        FalseButtonAlertDescription: "అది మీకు కూడా తెలుసు",
        SorryButtonText: "క్షమించు!",
        IntroductionText: "బొమ్మలను ఇచ్చిన  గడువు లోపల  లెక్కిస్తే  మీరు గెలిచినట్లు",
        IntroductionTitle: "ఎలా ఆడాలి?",
        LevelSelctionTitle: "మీ స్థాయిని ఎంచుకోండి",
        LevelOneTitle: "1 వ స్థాయి",
        LevelTwoTitle: "2 వ స్థాయి",
        LevelThreeTitle: "3 వ స్థాయి",
        LevelFourTitle: "4 వ స్థాయి",
        LevelTitleText: "స్థాయి",
        RoundTitleText: "రౌండ్",
        GetStartedButtonText: "ఆట ప్రారంభించు",
        NextRoundButtonText: "తదుపరి రౌండ్",
        ResultFailText: 'మళ్ళీ ప్రయత్నించు',
        ResultPassText: 'ఇది సరైన ఎంపిక',
        ResultHelpText: 'సరైన సమాధానం ఎంచుకోండి',
        SelectCountHelpText: 'గణనను ఎంచుకోండి',
        ResultSummaryTitle: 'ఆట ఫలితాలు',
        TotalRoundsTitle: 'మొత్తం రౌండ్లు',
        PassResultTitle: 'సరైనవి',
        FailResultTitle: 'తప్పులు',
        ScoreTitle: 'ఆటలో పాయింట్లు',
        GameOverTitle: 'ఆట సమాప్తం'
    }
}